/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as artemisZkVotingSol from "./ArtemisZkVoting.sol";
export type { artemisZkVotingSol };
import type * as verifierSol from "./Verifier.sol";
export type { verifierSol };
